# Assignment #1.3: Making Sense of the World

Data sources: [World Bank Open Data](https://data.worldbank.org)
- [Population, total](https://data.worldbank.org/indicator/SP.POP.TOTL)
- [Land area (sq. km)](https://data.worldbank.org/indicator/AG.LND.TOTL.K2)

### To Complete this assignment
- On an essay question, make your answer concise.
- On coding questions, assign the result of each task to the given variable in each cell unless stated otherwise. In other words, add the code for each task after the equal sign. Of course, you can use more variables to hold intermediate values before the final output. In addition, <span style="color:red">Use as much NumPy, pandas, PyPlot, and Seaborn as much as possible. They will make your life easier by not having to write condition and iteration statements.</span> 

1. Is the data source we use for this assignment trustable? Justify.

*Write your answer here.*

2. Import the necessary dependencies.

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

3. Load the world population dataset by setting the **country code column** to be the row label.

In [21]:
df_world = pd.read_csv("./data/world_population.csv").T
df_world.columns = df_world.loc['Country Code']
df_world

Country Code,ABW,AFE,AFG,AFW,AGO,ALB,AND,ARB,ARE,ARG,...,VIR,VNM,VUT,WLD,WSM,XKX,YEM,ZAF,ZMB,ZWE
Country Name,Aruba,Africa Eastern and Southern,Afghanistan,Africa Western and Central,Angola,Albania,Andorra,Arab World,United Arab Emirates,Argentina,...,Virgin Islands (U.S.),Vietnam,Vanuatu,World,Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
Country Code,ABW,AFE,AFG,AFW,AGO,ALB,AND,ARB,ARE,ARG,...,VIR,VNM,VUT,WLD,WSM,XKX,YEM,ZAF,ZMB,ZWE
Indicator Name,"Population, total","Population, total","Population, total","Population, total","Population, total","Population, total","Population, total","Population, total","Population, total","Population, total",...,"Population, total","Population, total","Population, total","Population, total","Population, total","Population, total","Population, total","Population, total","Population, total","Population, total"
Indicator Code,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,...,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL,SP.POP.TOTL
1960,54208.0,130836765.0,8996967.0,96396419.0,5454938.0,1608800.0,13410.0,92197715.0,92417.0,20481781.0,...,32500.0,32670048.0,63689.0,3032156070.0,108627.0,947000.0,5315351.0,17099836.0,3070780.0,3776679.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017,105361.0,626392880.0,36296111.0,423769930.0,29816769.0,2873457.0,76997.0,411942825.0,9487206.0,44044811.0,...,107281.0,94600643.0,285499.0,7519371102.0,195358.0,1791003.0,27834811.0,57009751.0,16853608.0,14236599.0
2018,105846.0,643090131.0,37171922.0,435229381.0,30809787.0,2866376.0,77008.0,419851989.0,9630966.0,44494502.0,...,107001.0,95545959.0,292675.0,7602716232.0,196128.0,1797085.0,28498683.0,57792520.0,17351714.0,14438812.0
2019,106310.0,660046272.0,38041757.0,446911598.0,31825299.0,2854191.0,77146.0,427870273.0,9770526.0,44938712.0,...,106669.0,96462108.0,299882.0,7683806444.0,197093.0,1788878.0,29161922.0,58558267.0,17861034.0,14645473.0
2020,106766.0,677243299.0,38928341.0,458803476.0,32866268.0,2837849.0,77265.0,436080728.0,9890400.0,45376763.0,...,106290.0,97338583.0,307150.0,7763932702.0,198410.0,1790133.0,29825968.0,59308690.0,18383956.0,14862927.0
2021,107195.0,694665117.0,39835428.0,470898870.0,33933611.0,2811666.0,77354.0,444517783.0,9991083.0,45808747.0,...,105870.0,98168829.0,314464.0,7836630792.0,200144.0,1806279.0,30490639.0,60041996.0,18920657.0,15092171.0

4. Notice that we do not need the "Indicator Name" and	"Indicator Code". So let's removed it from `df_world`. (Save the result in the same variable.)

In [26]:
df_world = df_world.drop(labels=["Indicator Name", "Indicator Code"], axis = 0, inplace=False)
df_world

Country Code,ABW,AFE,AFG,AFW,AGO,ALB,AND,ARB,ARE,ARG,...,VIR,VNM,VUT,WLD,WSM,XKX,YEM,ZAF,ZMB,ZWE
Country Name,Aruba,Africa Eastern and Southern,Afghanistan,Africa Western and Central,Angola,Albania,Andorra,Arab World,United Arab Emirates,Argentina,...,Virgin Islands (U.S.),Vietnam,Vanuatu,World,Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
Country Code,ABW,AFE,AFG,AFW,AGO,ALB,AND,ARB,ARE,ARG,...,VIR,VNM,VUT,WLD,WSM,XKX,YEM,ZAF,ZMB,ZWE
1960,54208.0,130836765.0,8996967.0,96396419.0,5454938.0,1608800.0,13410.0,92197715.0,92417.0,20481781.0,...,32500.0,32670048.0,63689.0,3032156070.0,108627.0,947000.0,5315351.0,17099836.0,3070780.0,3776679.0
1961,55434.0,134159786.0,9169406.0,98407221.0,5531451.0,1659800.0,14378.0,94724540.0,100801.0,20817270.0,...,34300.0,33666111.0,65700.0,3071596055.0,112112.0,966000.0,5393034.0,17524533.0,3164330.0,3905038.0
1962,56234.0,137614644.0,9351442.0,100506960.0,5608499.0,1711319.0,15379.0,97334438.0,112112.0,21153042.0,...,35000.0,34683410.0,67793.0,3124561005.0,115768.0,994000.0,5473671.0,17965733.0,3260645.0,4039209.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017,105361.0,626392880.0,36296111.0,423769930.0,29816769.0,2873457.0,76997.0,411942825.0,9487206.0,44044811.0,...,107281.0,94600643.0,285499.0,7519371102.0,195358.0,1791003.0,27834811.0,57009751.0,16853608.0,14236599.0
2018,105846.0,643090131.0,37171922.0,435229381.0,30809787.0,2866376.0,77008.0,419851989.0,9630966.0,44494502.0,...,107001.0,95545959.0,292675.0,7602716232.0,196128.0,1797085.0,28498683.0,57792520.0,17351714.0,14438812.0
2019,106310.0,660046272.0,38041757.0,446911598.0,31825299.0,2854191.0,77146.0,427870273.0,9770526.0,44938712.0,...,106669.0,96462108.0,299882.0,7683806444.0,197093.0,1788878.0,29161922.0,58558267.0,17861034.0,14645473.0
2020,106766.0,677243299.0,38928341.0,458803476.0,32866268.0,2837849.0,77265.0,436080728.0,9890400.0,45376763.0,...,106290.0,97338583.0,307150.0,7763932702.0,198410.0,1790133.0,29825968.0,59308690.0,18383956.0,14862927.0
2021,107195.0,694665117.0,39835428.0,470898870.0,33933611.0,2811666.0,77354.0,444517783.0,9991083.0,45808747.0,...,105870.0,98168829.0,314464.0,7836630792.0,200144.0,1806279.0,30490639.0,60041996.0,18920657.0,15092171.0

5. Load the land-area dataset by setting the **country code column** to be the row label.

In [28]:
df_areas = pd.read_csv("./data/land_areas.csv").T
df_areas.columns = df_areas.loc['Country Code']
df_areas

Country Code,ABW,AFE,AFG,AFW,AGO,ALB,AND,ARB,ARE,ARG,...,VIR,VNM,VUT,WLD,WSM,XKX,YEM,ZAF,ZMB,ZWE
Country Name,Aruba,Africa Eastern and Southern,Afghanistan,Africa Western and Central,Angola,Albania,Andorra,Arab World,United Arab Emirates,Argentina,...,Virgin Islands (U.S.),Vietnam,Vanuatu,World,Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
Country Code,ABW,AFE,AFG,AFW,AGO,ALB,AND,ARB,ARE,ARG,...,VIR,VNM,VUT,WLD,WSM,XKX,YEM,ZAF,ZMB,ZWE
1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1961,180.0,14571611.0,652230.0,9046580.0,1246700.0,27400.0,470.0,13611451.0,71020.0,2736690.0,...,350.0,325490.0,12190.0,129629034.469,2830.0,NaN,527970.0,1213090.0,743390.0,386850.0
1962,180.0,14571611.0,652230.0,9046580.0,1246700.0,27400.0,470.0,13611451.0,71020.0,2736690.0,...,350.0,325490.0,12190.0,129629014.469,2830.0,NaN,527970.0,1213090.0,743390.0,386850.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017,180.0,14845135.053,652230.0,9045780.0,1246700.0,27400.0,470.0,13100530.0,71020.0,2736690.0,...,350.0,313403.0,12190.0,129979735.26,2780.0,NaN,527970.0,1213090.0,743390.0,386850.0
2018,180.0,14845150.143,652230.0,9045780.0,1246700.0,27400.0,470.0,13100530.0,71020.0,2736690.0,...,350.0,313429.0,12190.0,129980445.879,2780.0,NaN,527970.0,1213090.0,743390.0,386850.0
2019,180.0,14845162.404,652230.0,9045780.0,1246700.0,27400.0,470.0,13100547.0,71020.0,2736690.0,...,350.0,313429.0,12190.0,129980384.217,2780.0,NaN,527970.0,1213090.0,743390.0,386850.0
2020,180.0,14845123.094,652230.0,9045773.0,1246700.0,27400.0,470.0,13100549.0,71020.0,2736690.0,...,350.0,313429.0,12190.0,129979826.521,2780.0,NaN,527970.0,1213090.0,743390.0,386850.0
2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

6. Load the region-and-income dataset by setting the first column to be the row label.

In [33]:
df_reg = pd.read_csv("./data/regions_and_income.csv").T
df_reg.columns = df_reg.iloc[0]
df_reg

Country Code,ABW,AFE,AFG,AFW,AGO,ALB,AND,ARB,ARE,ARG,...,VIR,VNM,VUT,WLD,WSM,XKX,YEM,ZAF,ZMB,ZWE
Country Code,ABW,AFE,AFG,AFW,AGO,ALB,AND,ARB,ARE,ARG,...,VIR,VNM,VUT,WLD,WSM,XKX,YEM,ZAF,ZMB,ZWE
Region,Latin America & Caribbean,NaN,South Asia,NaN,Sub-Saharan Africa,Europe & Central Asia,Europe & Central Asia,NaN,Middle East & North Africa,Latin America & Caribbean,...,Latin America & Caribbean,East Asia & Pacific,East Asia & Pacific,NaN,East Asia & Pacific,Europe & Central Asia,Middle East & North Africa,Sub-Saharan Africa,Sub-Saharan Africa,Sub-Saharan Africa
IncomeGroup,High income,NaN,Low income,NaN,Lower middle income,Upper middle income,High income,NaN,High income,Upper middle income,...,High income,Lower middle income,Lower middle income,NaN,Lower middle income,Upper middle income,Low income,Upper middle income,Low income,Lower middle income

7. Find the population density of each country in `df_world` by year.<br>
*Tip*: Do dataframe calculation without non-numerical columns.

In [48]:
pop_density = df_world.iloc[2:, :]
pop_density

Country Code,ABW,AFE,AFG,AFW,AGO,ALB,AND,ARB,ARE,ARG,...,VIR,VNM,VUT,WLD,WSM,XKX,YEM,ZAF,ZMB,ZWE
1960,54208.0,130836765.0,8996967.0,96396419.0,5454938.0,1608800.0,13410.0,92197715.0,92417.0,20481781.0,...,32500.0,32670048.0,63689.0,3032156070.0,108627.0,947000.0,5315351.0,17099836.0,3070780.0,3776679.0
1961,55434.0,134159786.0,9169406.0,98407221.0,5531451.0,1659800.0,14378.0,94724540.0,100801.0,20817270.0,...,34300.0,33666111.0,65700.0,3071596055.0,112112.0,966000.0,5393034.0,17524533.0,3164330.0,3905038.0
1962,56234.0,137614644.0,9351442.0,100506960.0,5608499.0,1711319.0,15379.0,97334438.0,112112.0,21153042.0,...,35000.0,34683410.0,67793.0,3124561005.0,115768.0,994000.0,5473671.0,17965733.0,3260645.0,4039209.0
1963,56699.0,141202036.0,9543200.0,102691339.0,5679409.0,1762621.0,16407.0,100034191.0,125130.0,21488916.0,...,39800.0,35721213.0,69944.0,3189655687.0,119552.0,1022000.0,5556767.0,18423157.0,3360099.0,4178726.0
1964,57029.0,144920186.0,9744772.0,104953470.0,5734995.0,1814135.0,17466.0,102832792.0,138049.0,21824427.0,...,40800.0,36780001.0,72116.0,3255145692.0,123346.0,1050000.0,5641598.0,18896303.0,3463211.0,4322854.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017,105361.0,626392880.0,36296111.0,423769930.0,29816769.0,2873457.0,76997.0,411942825.0,9487206.0,44044811.0,...,107281.0,94600643.0,285499.0,7519371102.0,195358.0,1791003.0,27834811.0,57009751.0,16853608.0,14236599.0
2018,105846.0,643090131.0,37171922.0,435229381.0,30809787.0,2866376.0,77008.0,419851989.0,9630966.0,44494502.0,...,107001.0,95545959.0,292675.0,7602716232.0,196128.0,1797085.0,28498683.0,57792520.0,17351714.0,14438812.0
2019,106310.0,660046272.0,38041757.0,446911598.0,31825299.0,2854191.0,77146.0,427870273.0,9770526.0,44938712.0,...,106669.0,96462108.0,299882.0,7683806444.0,197093.0,1788878.0,29161922.0,58558267.0,17861034.0,14645473.0
2020,106766.0,677243299.0,38928341.0,458803476.0,32866268.0,2837849.0,77265.0,436080728.0,9890400.0,45376763.0,...,106290.0,97338583.0,307150.0,7763932702.0,198410.0,1790133.0,29825968.0,59308690.0,18383956.0,14862927.0
2021,107195.0,694665117.0,39835428.0,470898870.0,33933611.0,2811666.0,77354.0,444517783.0,9991083.0,45808747.0,...,105870.0,98168829.0,314464.0,7836630792.0,200144.0,1806279.0,30490639.0,60041996.0,18920657.0,15092171.0

8. Merge the population-density and region-and-income datasets.<br>*Tip:* Think about which column is best to merge on.

In [52]:
df_merged = pop_density.merge(df_reg, left_on="ABW", right_on="A")
df_merged

KeyError: 'Region'

9. List the number of missing values in `df_merged` by column. Put this list as a `Series` in `null_counts`.

In [ ]:
null_counts =

10. Drop columns that has no data in them (aka data in every row in that column is missing) in `df_merged`. Save the result in the same dataframe.

11. Drop rows with missing data

In [ ]:
df_clean =

12. Many countries have had policies about birth rates. Some would like their citizens to have less babies during a period of time while the new trend is to encourage people to have more than one child per family. Does the number of population have something to do with the wealth of a country? Or else?<br><br>
12-A. Use the given datasets to create a visualization that help us investigate if the population density of a country has something to do with the level of income. Feel free to transform and select types of visualization that would best illustrate this issue. Because the time limit, I suggest that you pick only two or three columns to visualize instead of delivering a set of visualization for a whole data set.

12-B. Based on your visualization, briefly discuss your observation on the issue to invetigate. If the visualization does not have any meaningful information, suggest another way of transforming data and/or an alternate type of visualization. (You do not need to create another visualization with code here.)

*Write your discussion here.*